image: docker:stable

stages:
- build
- deploy

variables:
  WEB_BACKOFFICE_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_web_backoffice:$CI_COMMIT_REF_SLUG
  WEB_API_MOBILE_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_web_api_mobile:$CI_COMMIT_REF_SLUG
  PHP_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_php:$CI_COMMIT_REF_SLUG
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_CERTDIR: ""

services:
    - docker:stable-dind

build_web_api:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "API_URL=$CI_ENVIRONMENT_URL/api" -t $WEB_API_MOBILE_IMAGE_NAME -f nginx-api-mobile.dockerfile .
    - docker push $WEB_API_MOBILE_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $FRONTURL
  only:
    - master
    - staging
    - prod

build_web_backoffice:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "API_URL=$CI_ENVIRONMENT_URL/api" -t $WEB_BACKOFFICE_IMAGE_NAME -f nginx-backoffice.dockerfile .
    - docker push $WEB_BACKOFFICE_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $BACKOFFICEURL
  only:
    - master
    - staging
    - prod

build_php:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $PHP_IMAGE_NAME -f phpcomposer.dockerfile .
    - docker push $PHP_IMAGE_NAME
  only:
    - master
    - staging
    - prod

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_ENV --stack $RANCHER_STACK --service $RANCHER_STS_PHP_SERVICE --start-before-stopping
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_ENV --stack $RANCHER_STACK --service $RANCHER_STS_WEB_BACKOFFICE_SERVICE --start-before-stopping
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_ENV --stack $RANCHER_STACK --service $RANCHER_STS_WEB_API_MOBILE_SERVICE --start-before-stopping
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $FRONTURL
  only:
    - staging
    - prod
