image: docker:stable

stages:
- build
- deploy

variables:
  WEB_BACKOFFICE_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_web_backoffice:$CI_COMMIT_REF_SLUG
  WEB_API_MOBILE_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_web_api_mobile:$CI_COMMIT_REF_SLUG
  PHP_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_php:$CI_COMMIT_REF_SLUG
  GIT_SUBMODULE_STRATEGY: recursive

build_web_api:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "API_URL=$FRONTURL/api" -t $WEB_API_MOBILE_IMAGE_NAME -f nginx-api-mobile.dockerfile .
    - docker push $WEB_API_MOBILE_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
    - master
    - staging
    - prod

build_web_backoffice:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "API_URL=$BACKOFFICEURL/api" -t $WEB_BACKOFFICE_IMAGE_NAME -f nginx-backoffice.dockerfile .
    - docker push $WEB_BACKOFFICE_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
    - master
    - staging
    - prod

build_php:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $PHP_IMAGE_NAME -f phpcomposer.dockerfile .
    - docker push $PHP_IMAGE_NAME
  only:
    - master
    - staging
    - prod

deploy:
  image:
    name: jrisp/kubehelper:latest
    entrypoint: [""]
  stage: deploy
  dependencies:
    - build_web_api
    - build_web_backoffice
    - build_php
  script:
    - NS=sts
    - kubectl config set-cluster k8s --server="$KUBE_URL" --certificate-authority="$KUBE_CA_PEM_FILE"
    - kubectl config set-credentials gitlab-admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=gitlab-admin
    - kubectl config use-context default
    - kubectl apply -f k8s/namespace.yml
    - cp ${POSTGRES_SECRETS} k8s/overlays/$CI_COMMIT_REF_SLUG/postgres.env
    - cp ${STS_SECRETS} k8s/overlays/$CI_COMMIT_REF_SLUG/sts.env
    - kubectl apply -k k8s/overlays/$CI_COMMIT_REF_SLUG
    - kubectl -n ${NS} rollout restart deployment ${NS}-php
    - kubectl -n ${NS} rollout restart deployment ${NS}-bo
    - kubectl -n ${NS} rollout restart deployment ${NS}-web
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
   - staging
   - prod
