image: docker:stable

stages:
- build
- deploy

variables:
  WEB_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_web:$CI_COMMIT_REF_SLUG
  PHP_IMAGE_NAME: $CI_REGISTRY_IMAGE/sts_php:$CI_COMMIT_REF_SLUG
  GIT_SUBMODULE_STRATEGY: recursive
  
build_web_staging:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "API_URL=$CI_ENVIRONMENT_URL/api" -t $WEB_IMAGE_NAME -f nginx-prod.dockerfile .
    - docker push $WEB_IMAGE_NAME
  environment:
    name: staging
    url: http://sts-pprd.medialab.sciences-po.fr
  only:
    - staging
   
build_web_prod:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "API_URL=$CI_ENVIRONMENT_URL/api" -t $WEB_IMAGE_NAME -f nginx-prod.dockerfile .
    - docker push $WEB_IMAGE_NAME
  environment:
    name: production
    url: https://sts.medialab.sciences-po.fr
  only:
    - production

build_php:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $PHP_IMAGE_NAME -f phpcomposer.dockerfile .
    - docker push $PHP_IMAGE_NAME
  only:
    - staging
    - production
   
deploy_staging:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_STAGING_ENV --stack $RANCHER_STACK --service $RANCHER_STS_PHP_SERVICE --start-before-stopping
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_STAGING_ENV --stack $RANCHER_STACK --service $RANCHER_STS_WEB_SERVICE --start-before-stopping
  environment:
    name: staging
    url: http://sts-pprd.medialab.sciences-po.fr
  only:
    - staging
  

deploy_production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_PRODUCTION_ENV --stack $RANCHER_STACK --service $RANCHER_STS_PHP_SERVICE --start-before-stopping
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_PRODUCTION_ENV --stack $RANCHER_STACK --service $RANCHER_STS_WEB_SERVICE --start-before-stopping
  environment:
    name: production
    url: https://sts.medialab.sciences-po.fr
  only:
    - production