version: "2"
services:
  api:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./ScienceTrotterS_API:/api
      - ./api.conf:/etc/nginx/conf.d/default.conf
      - api_ressources:/api/public/ressources
    networks:
      - backend
  backoffice:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./ScienceTrotterS_backoffice:/backoffice
      - ./backoffice.conf:/etc/nginx/conf.d/default.conf
      - backoffice_ressources:/backoffice/public/ressources
    networks:
      - backend
  mobile_app:
    image: mobile_app:latest
    ports:
      - "8081:80"
  php:
    image: phpcomposer:latest
    env_file:
      - postgres.env
      - php.env
    networks:
      - backend
    volumes:
      - api_ressources:/api/public/ressources
      - backoffice_ressources:/backoffice/public/ressources
  db:
    image: postgres:latest
    networks:
      - backend
    env_file:
      - postgres.env
networks:
  backend:
volumes:
     backoffice_ressources:
     api_ressources: 