version: "2"
services:
  web:
    image: scpomedialab/sts_web:prod
    build: 
      dockerfile: nginx-prod.dockerfile
      context: .
    ports:
      - "80:80"
    links:
      - php:php
    networks:
      - backend
    depends_on:
      - php
      - db
    volumes:
      - backoffice_ressources:/backoffice/public/ressources
      - api_ressources:/api/public/ressources
  php:
    build:
      dockerfile: phpcomposer.dockerfile
      context: .
    image: scpomedialab/sts_php:prod
    env_file:
      - postgres.env
      - php.env
    networks:
      - db
      - backend
    depends_on:
      - db
    volumes:
      - backoffice_ressources:/backoffice/public/ressources
  db:
    image: postgres:latest
    networks:
      - db
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  backend:
  db:
volumes:
  backoffice_ressources:
  api_ressources:
  postgres_data:
