version: "2"
services:
  web:
    image: scpomedialab/sts_web:prod
    build: 
      dockerfile: nginx-prod.dockerfile
      context: .
    ports:
      - "5000:5000"
      - "80:80"
    links:
      - php:php
    networks:
      - backend
    depends_on:
      - php
      - db
  php:
    build:
      dockerfile: phpcomposer.dockerfile
      context: .
    image: scpomedialab/sts_php:prod
    env_file:
      - postgres.env
      - php.env
    networks:
      - db
      - backend
    depends_on:
      - db
  db:
    image: postgres:latest
    networks:
      - db
    env_file:
      - postgres.env
networks:
  backend:
  db:
