version: "2"
services:
  web_api_mobile:
    image: scpomedialab/sts_web_api_mobile:prod
    build: 
      dockerfile: nginx-api-mobile.dockerfile
      context: .
    ports:
      - "8080:80"
    links:
      - php:php
    networks:
      - backend
    environment:
      - UPLOAD_PATH=${UPLOAD_PATH}
    env_file:
      - php.env
    depends_on:
      - php
      - db
    volumes:
      - upload:${UPLOAD_PATH}:ro
  web_backoffice:
    image: scpomedialab/sts_web_backoffice:prod
    build: 
      dockerfile: nginx-backoffice.dockerfile
      context: .
    ports:
      - "8081:80"
    links:
      - php:php
    networks:
      - backend
    environment:
      - UPLOAD_PATH=${UPLOAD_PATH}
    env_file:
      - php.env
    depends_on:
      - php
      - db
    volumes:
      - upload:${UPLOAD_PATH}:ro
  php:
    build:
      dockerfile: phpcomposer.dockerfile
      context: .
    image: scpomedialab/sts_php:prod
    environment:
      - UPLOAD_PATH=${UPLOAD_PATH}
    env_file:
      - postgres.env
      - php.env
    networks:
      - db
      - backend
    depends_on:
      - db
    volumes:
      - upload:${UPLOAD_PATH}
  db:
    image: postgres:latest
    networks:
      - db
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  backend:
  db:
volumes:
  upload:
  postgres_data:
