apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sts

namePrefix: sts-

bases:
  - ../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: development

secretGenerator:
- name: postgres
  literals:
    - db_name=STS
    - user_name=STS
    - user_password=very_secret

- name: sts
  literals:
    - api_pass=admin
    - map_api_key=very_secret

images:
  - name: gitlab.sciences-po.fr:4567/medialab/sciencetrotters_docker/sts_web_api_mobile
    newTag: 'master'
  - name: gitlab.sciences-po.fr:4567/medialab/sciencetrotters_docker/sts_php
    newTag: 'master'
  - name: gitlab.sciences-po.fr:4567/medialab/sciencetrotters_docker/sts_web_backoffice
    newTag: 'master'
