#!/bin/bash -xe
[ -n "$SOURCE_BRANCH" ] || SOURCE_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
if [ "$SOURCE_BRANCH" == "prod" ]; then 
    docker build --build-arg "API_URL=https://sts.medialab.sciences-po.fr/api" -t $IMAGE_NAME .
elif [ "$SOURCE_BRANCH" == "staging" ]; then
    docker build --build-arg "API_URL=http://sts-pprd.medialab.sciences-po.fr/api" -t $IMAGE_NAME .
fi
