apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-backup.yml
  - db/pvc.yml
  - db/deployment.yml
  - db/service.yml
  - db/cronjob.yml
  - php/pvc.yml
  - php/deployment.yml
  - php/service.yml
  - bo/deployment.yml
  - bo/service.yml
  - web/deployment.yml
  - web/service.yml

commonLabels:
  owner: medialab
  app: sts
