apiVersion: apps/v1
kind: Deployment
metadata:
  name: bo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bo
  template:
    metadata:
      labels:
        component: bo
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: bo
          image: gitlab.sciences-po.fr:4567/medialab/sciencetrotters_docker/sts_web_backoffice:latest
          env:
            - name: UPLOAD_PATH
              value: '/ressources/upload/'
            - name: API_URL
              value: 'sts-web.sts.svc.cluster.local:5000'
            - name: PHP_HOST
              value: 'sts-php.sts.svc.cluster.local'
            - name: PHP_PORT
              value: '9000'
          imagePullPolicy: Always

          volumeMounts:
            - name: upload-vol
              mountPath: /ressources/upload
      volumes:
        - name: upload-vol
          persistentVolumeClaim:
            claimName: upload-pvc
